### ISSUE TITLE
message ordering

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#462]
when bears send log messages they are ordered within themselves which is good.

However when a bear sends log messages and returns a result the result may be printed between all the log messages, example:

```
[DEBUG][13:46:52] |||| DISP: i
[DEBUG][13:46:52] |||| DEFI: <coalib.bearlib.parsing.clang.cindex.Cursor object at 0x7fd54009ebf8>


/home/lasse/prog/clang-ast-bear/samples/sample.c
[DEBUG][13:46:52] ||| Got child:
|    |    | [NORMAL] ClangASTBear:
|    |    | COUNT DICT IS: {'asd': [0], 'i': [3], 't': [1], 'g': [1]}
[DEBUG][13:46:52] ||| SCOP: 1
|    |    | The following options are applicable to this result (choose 0 for no action):
[DEBUG][13:46:52] ||| KIND: CursorKind.BINARY_OPERATOR
|    |    |  1: Open a temporary clone of the file in an editor.
[DEBUG][13:46:52] ||| USR : b''
[DEBUG][13:46:52] ||| DISP:
[DEBUG][13:46:52] |||| Got child:
|    |    | Please enter the number of the action you want to execute. [DEBUG][13:46:52] |||| SCOP: 1
[DEBUG][13:46:52] |||| KIND: CursorKind.UNEXPOSED_EXPR
[DEBUG][13:46:52] |||| USR : b''
[DEBUG][13:46:52] |||| DISP: i
```

**Comment by Makman2** [comment]
https://github.com/coala-analyzer/coala/issues/933 doesn't need a logger thread when implemented so there can't go something wrong.

**Comment by Makman2** [comment]
Btw I think this is already fixed...

**Comment by sils1297** [comment]
this is certainly not fixed. And I don't see how this'll be solved?

**Comment by Makman2** [comment]
since there's no logger thread any more the order of `Result` and log-message printing can be controlled.

**Comment by tushar-rishav** [comment]
@sils1297  Is this fixed?

**Comment by sils1297** [comment]
Still not why keep people thinking that :P

**Comment by tushar-rishav** [comment]
@sils1297  Great! I'll give a try!

**Comment by Makman2** [comment]
@tushar-rishav this will get fixed when I'm done with the next-gen-core design, that's what my statement refers to (have forgotten to write that). I think I can block this issue, right @sils1297 ?

**Comment by tushar-rishav** [comment]
@Makman2 Ah. Cool!

**Comment by Makman2** [comment]
blocking that issue, see #933.
